version: '2'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    build: .
    command: uwsgi --ini uwsgi.ini
    working_dir: /code/emonx
    volumes:
      - ./emonx:/code/emonx
    ports:
      - "8000:8000"