version: '2'
 
services:
  db:
    image: mysql:5.7
    container_name: mysql-server
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "lbr123"
      MYSQL_DATABASE: "djangodb"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"
    volumes:
      - ./db/my.conf:/etc/mysql/my.cnf
      - ./db/data:/var/lib/mysql
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    build: .
    command: uwsgi --ini uwsgi.ini
    working_dir: /code/web
    volumes:
      - ./emonx:/code/web
    ports:
      - "8000:8000"
    depends_on:
      - db

